spring:
  application:
    name: trusticket
  elasticsearch:
    uri: localhost:9200



# Swagger
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
    - /login

# Exception handler

error:
  printStackTrace: true # Stack trace ?? ??
  printStackTraceLine: 10 # Stack trace ?? ? ?

